#ifndef BUF_MAN_INDEXES
#define BUF_MAN_INDEXES

#define FROMSRC_TOTAL_GLOBAL_BUFS 9
#define FROMSRC_TOTAL_LOCAL_BUFS 4

#define FROMSRC_ADJ_LOCAL_CODE(i) (i - FROMSRC_LOCAL_FUNC)
#define IS_GLOBAL_CODE(c) (c <= FROMSRC_TOTAL_GLOBAL_BUFS)

enum{
	FROMSRC_ORDER,
	
	FROMSRC_LIB_FUNC,
	FROMSRC_LIB_VAR,
	FROMSRC_GLOBAL_FUNC,
	FROMSRC_GLOBAL_VAR,

	FROMSRC_FROM_LUA,
	FROMSRC_FROM_HEAD,

	FROMSRC_CONSTANT,
	FROMSRC_USE_OR_CALL,

	FROMSRC_LOCAL_FUNC,
	FROMSRC_LOCAL_VAR,
	FROMSRC_LOCAL_SELF_PARAM,
	FROMSRC_LOCAL_ALIGN_PARA,
};

#endif
