#!/usr/bin/env bash

./scripts/create-main args

declare -i first=0

clear
while read _args; do
	echo -e "lim $_args\n"
	
	if [[ ! -z $_args ]] || [[ $first -eq 0 ]]; then
		$TMP/exe $_args
	fi

	if [[ $? -ne 0 ]]; then
		echo -e "An error occur\nTIP: check \"./tests/.tmp/exe\" with GDB"
		exit 1
	fi

	first=1

	# TODO: improve it + add test number/index
	printf "Next in 2.5s..."
	sleep 2.5
	clear
done < $(get_args_path args)

unset commands commands_length
#rm -r .tmp
