#!/usr/bin/env bash


declare _main_c_path=$(get_main_path $ARG_TARGET)
declare _files=$(      read_file $ARG_TARGET/files  1 1)
declare _main=$(       read_file $ARG_TARGET/main.c 1 0)


echo "$_main" > $MAIN
gcc -g $_main_c_path $_files -o $EXE


if [[ $? != "0" ]]; then
	echo -e "\nCompilation error.\nThe tests process was sttoped."
	exit 1
fi
