#!/usr/bin/env bash


_main_c_path=$(get_main_path $RUN_ARG)
_files=$(      read_file $RUN_ARG/files    1 1)
_includes=$(   read_file $RUN_ARG/includes 0 1)
_main=$(       read_file $RUN_ARG/main.c   1 0)


echo "$_main" > $MAIN
gcc -g $_main_c_path $_files $_includes -o $EXE > $LOG 2>&1


if [[ $? != "0" ]]; then
	cat $LOG
	echo -e "\nCompilation error.\nThe tests process was sttoped."
	rm_tmp_dir
	exit 1
fi
