#!/usr/bin/env bash


_main_c_path=$(get_main_path $ARG_TARGET)
_files=$(      read_file $ARG_TARGET/files    1 1)
_includes=$(   read_file $ARG_TARGET/includes 0 1)
_main=$(       read_file $ARG_TARGET/main.c   1 0)


echo "$_main" > $MAIN
gcc -g $_main_c_path $_files $_includes -o $EXE


if [[ $? != "0" ]]; then
	echo -e "\nCompilation error.\nThe tests process was sttoped."
	rm_tmp_dir
	exit 1
fi
