#!/usr/bin/env bash

declare cur_arg

declare -i is_first=0 is_error=0
declare -i index=$(wc -l < $(get_args_path $ARG_TARGET))


clear
while read cur_args; do
	echo -e "$index) lim $cur_args\n"
	
	if [[ ! -z $cur_args ]] || [[ $is_first -eq 0 ]]; then
		$TMP/exe $cur_args > $LOG
		is_error=$?
	fi

	if [[ $ARG_BROKEN -ne 3 ]] || [[ $is_error -eq 1 ]]; then
		cat $LOG
	fi

	if [[ $is_error -ne 0 ]]; then
		echo -e "\n[!] AN ERROR OCCUR [!]\n"

		debug_exe -1
	fi

	is_first=1
	index=$index-1

	if [[ $ARG_BROKEN -ne 3 ]] || [[ $is_error -ne 0 ]]; then
		read -p "Press [ENTER] to continue: " < /dev/tty
	fi

	clear
done < $(get_args_path $ARG_TARGET)


unset cur_arg is_first is_error index
