#!/usr/bin/env bash

declare cur_arg
declare error_status="0"

declare -i is_first=0
declare -i index=$(wc -l < $(get_args_path $RUN_ARG))


clear
while read cur_args; do
	echo -e "$index) lim $cur_args\n"
	
	if [[ ! -z $cur_args ]] || [[ $is_first -eq 0 ]]; then
		$TMP/exe $cur_args
	fi

	if [[ $? -ne 0 ]]; then
		echo -e "\n[!] AN ERROR OCCUR [!]\nSee $BROK/\n\n"
		error_status="1"

		[[ ! -d $BROK ]] && mkdir $BROK
		cp $TMP/exe $BROK/lim
	fi

	is_first=1
	index=$index-1

	read -p "Press [ENTER] to continue: " < /dev/tty
	clear
done < $(get_args_path $RUN_ARG)


[[ $error_status = "0" ]] && [[ -d $BROK ]] && rm -r $BROK
unset cur_arg error_status is_first index
